language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot_and_aws_soobinhand *
  - mkdir -p deploy
  - mv springboot_and_aws_soobinhand.zip deploy/springboot_and_aws_soobinhand.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-and-aws-soobinhand-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot_and_aws_soobinhand_build
    key: springboot-and-aws-soobinhand.zip
    bundle-type: zip
    application: springboot-and-aws-soobinhand
    deployment_group: springboot-and-aws-soobinhand-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - chelsea9528@naver.com

